# Generated by Django 4.2.2 on 2023-08-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sessioninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionInfo',
        ),
    ]
