# Generated by Django 4.2.2 on 2023-09-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.TextField()),
                ('encrypted_password', models.TextField()),
                ('encrypted_key', models.TextField()),
                ('tag', models.TextField()),
                ('Login_informations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifier.login_informations')),
            ],
        ),
    ]
