# Generated by Django 4.2.2 on 2023-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_informations',
            name='password',
            field=models.TextField(),
        ),
    ]
