# Generated by Django 4.2.2 on 2023-09-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0002_password_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password_storage',
            name='encrypted_password',
        ),
    ]
