# Generated by Django 4.2.2 on 2023-09-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0004_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password_storage',
            name='Login_informations_id',
        ),
        migrations.AddField(
            model_name='login_informations',
            name='password_storage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='identifier.password_storage'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
